### ISSUE TITLE
GitCash test

### ISSUE THREAD

**Issue by linkdesu** [BlockABC/eos-tokens#28]
@GitCash 1000 bits for @longhuicode

**Comment by linkdesu** [comment]
@tesdsfsdfyukutikguikryujryufuihliol

**Comment by linkdesu** [comment]
@GitCash 1001 bits for @zgayjjf

**Comment by alwaysAn0n** [comment]
@GitCash 5000 bits for @longhuicode

**Comment by GitCash** [comment]
Hey **longhuicode**, user **alwaysAn0n** tipped you **5000 bits** in Bitcoin Cash ( ~ **$0.605** ).

*[Click here to claim it!](https://gitcash.io/claim/longhuicode)*

You can also add the "thumbs down" reaction to **alwaysAn0n**'s comment above to prevent future tips.

**Comment by alwaysAn0n** [comment]
@linkdesu I'm not sure why that didnt work for you

@GitCash 5000 bits for @zgayjjf and @longhuicode

**Comment by GitCash** [comment]
Hey **zgayjjf,@longhuicode**, user **alwaysAn0n** tipped you **5000 bits** in Bitcoin Cash ( ~ **$0.61** ).

*[Click here to claim it!](https://gitcash.io/)*

You can also add the "thumbs down" reaction to **alwaysAn0n**'s comment above to prevent future tips.

**Comment by GitCash** [comment]
Hey **zgayjjf,@longhuicode**, user **alwaysAn0n** tipped you **5000 bits** in Bitcoin Cash ( ~ **$0.61** ).

*[Click here to claim it!](https://gitcash.io/)*

You can also add the "thumbs down" reaction to **alwaysAn0n**'s comment above to prevent future tips.
