### ISSUE TITLE
how do i get write permissions?

### ISSUE THREAD

**Issue by coreycottrell** [BlockABC/eos-tokens#87]
forked it, created folder, added ,json and .png, trying to commit it to master but getting the insufficient permissions error.  
coreycmusic@gmail.com
![eos tokens json](https://user-images.githubusercontent.com/49536420/56473738-56968b00-643d-11e9-86bc-27e7a3fbb4bb.JPG)

**Comment by zgayjjf** [comment]
Looks like you know how to use github now.

**Comment by coreycottrell** [comment]
;)
1 full day of googling produced less than 10 minutes chatting w the founder
of EOS Bulgaria.  Thanks for the quick response!

**Comment by coreycottrell** [comment]
Apologies if this is a dumb question,  does appending this information
populate updates on wallets like eoslynx or the DEXes?  Currently my token
isnt on them.  Emailing w NewDex tomrw to discuss their protocol either
way.

Tks again for the quick reponse today!

**Comment by kriszrtina** [comment]
.
